# Use the latest Arch Linux base image
FROM archlinux:latest

# Update the package database and install necessary packages
RUN pacman -Syu --noconfirm bash bc git ffmpeg lilypond csound sox alsa-utils ecasound vim shellcheck

# Create a user and set up the home directory
RUN useradd -m -s /bin/bash linter

WORKDIR /home/linter

RUN mkdir /home/linter/test-shellcheck-mount-container/

ENTRYPOINT ["shellcheck"]
