  name: Pull code to user device
  uses: webfactory/ssh-agent@v0.5.0
  with:
    ssh-private-key: ${{ secrets.USER_DEVICE_SSH_PRIVATE_KEY }}
    ssh-known-hosts: ${{ secrets.USER_DEVICE_SSH_KNOWN_HOSTS }}
    ssh-strict: true
  run: |
    ssh -o StrictHostKeyChecking=yes -A -t user@192.168.1.135 "cd $HOME/mmw/ && git pull origin develop"

       
