name: CI Workflow

on:
  workflow_dispatch:
    # Allows you to manually trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bats
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm bats

      - name: Run Bats test
        run: bats -f "Can set: project" test/mmw/mmw.bats

