name: Pull code to user device

on:
  push:
    branches:
      - develop

jobs:
  stage-the-dev-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.USER_DEVICE_SSH_PRIVATE_KEY }}

      - name: Pull code
        run: |
          ssh -o StrictHostKeyChecking=yes -A -t joel@192.168.1.135 "cd $HOME/mmw/ && git pull origin develop"
